### ISSUE TITLE
We're not lumberjacks.

### ISSUE THREAD

**Issue by mdb92nc** [mpk2/STAR-Vote#27]
I don't quite understand logging. Theoretically, should new machines connecting to STAR get the full log files? I recall this being discussed at our meeting in May, and I know there was discussion about opening a discreet socket between machines and beaming the log data, but I also recall someone suggesting that as long as the machine logs from when it comes online the logging and verification process can be preserved.

This is important largely due to issue #26. When a Supervisor machine comes online, it needs to figure out if the polls are open or not. As of right now, we have an event, [LastPollsOpenEvent](https://github.com/mdb92nc/STAR-Vote/blob/master/votebox/events/LastPollsOpenEvent.java) that notifies that the last polls opened event is being announced by a supervisor if the polls are currently opened. 

*Note: there may be a potential race condition if a machine comes online, inquires about the status of the polls, then the polls are closed, but a [LastPollsOpenEvent](https://github.com/mdb92nc/STAR-Vote/blob/master/votebox/events/LastPollsOpenEvent.java) is sent by a machine that hasn't received or processed the event yet. The new machine could query the poll status, hear that the polls are closed, and then hear the open event, resulting in all but the new Supervisor thinking the polls are closed.*

The current implementation holds up regardless of the log transmission policy ultimately decided on, but in the case we decide to transmit the whole log to every new machine, then we could also check the logs to verify that the polls are indeed opened (notably eliminating the race condition discussed above). Regardless, this needs to be vetted more with people who know more things than I do.

**Comment by mpk2** [comment]
@mdb92nc Could you refresh me on this and whether it was fixed?

**Comment by mdb92nc** [comment]
This was never fixed, but I don't think it needed to be necessarily. What we have in place now is okay, so for the implementation purposes I say we leave it as is.
